### ISSUE TITLE
配置选项可以添加一个抓取代理IP的响应时间在某个自定义值内

### ISSUE THREAD

**Issue by CL545740896** [Karmenzind/fp-server#1]
"url": "https://114.226.128.6:6666", "speed": "643.5837540626526"
像这样的代理 响应速度太慢了,后面使用的时候 还需要自己筛选 觉得不够人性化 
可以在配置文件里面设置一个值响应速度的值  抓取的时候 如果响应速度在小于这个值 则保存下来

**Comment by CL545740896** [comment]
http://www.data5u.com/free/index.html 无忧代理质量还不错

**Comment by Karmenzind** [comment]
谢谢反馈。
目前我用了[三个网站](https://github.com/Karmenzind/fp-server/blob/master/src/proxy_spider/spiders/__init__.py#L42)来检测代理可用性，检测每个代理时随即选取其中一个。网站不一样，而且都是国外的，所以这个速度只是个临时记录，参考意义不大。你用这些代理访问其他网站的时候，这个速度可能会和访问那三个网站不一样。
我后面研究一下更好的检测方法。

你的运行环境贴一下？

**Comment by CL545740896** [comment]
![n2fqi_ 7 zcjav 1rpsmzx](https://user-images.githubusercontent.com/27679586/41515236-215b434e-72e0-11e8-89aa-bb67873ef6c0.png)
![kjduyclh 0a 13 8lanfiv](https://user-images.githubusercontent.com/27679586/41515237-2299dafe-72e0-11e8-8bed-7a300f3e5ed1.png)
运行了一天之后 发现api返回不到值

**Comment by Karmenzind** [comment]
运行环境以及日志（如果设置的终端输出，截一下最后的几页）？

**Comment by Karmenzind** [comment]
这两个截图是在同一时间访问的是吧？再访问一下proxy，然后把日志输出贴上来？

**Comment by Karmenzind** [comment]
@CL545740896  我找到原因了，，，尴尬，，我忘记给scheme忽略大小写了= = 还好不是大bug，，，
![image](https://user-images.githubusercontent.com/17923071/41517857-e42eca16-72f0-11e8-8413-d870021d55d5.png)

**Comment by Karmenzind** [comment]
我今天看了一下代码，反应过来我写的speed判断方法有问题
实际上的限制时间是20秒，你看到的超过20秒的是代码计算错误

**Comment by Karmenzind** [comment]
https://github.com/Karmenzind/fp-server/commit/2d9807b7ed592775ee3224d9ba1620c4c7f5c709#diff-e2392ac801d7a9330d58f27f8092e404R67
增加了一个CHECK_TIMEOUT可以手动修改
暂时不作为正式设置
