### ISSUE TITLE
ip的有效检测准确性有待提高

### ISSUE THREAD

**Issue by amhoho** [Karmenzind/fp-server#18]
晚上用fp_server跑了个guzzle爬虫,采集的时候有许多都是无效ip
我甚至把config中的个数拔高到5000个,定时从3600改到300.
4000多个真正可用的不到10%
后来,我用另一个http://123.207.35.36:5010/get/的ip直接测试,准确率到80%.
这个说明我们的检测是不是不够到位.

**Comment by Karmenzind** [comment]
检测确实可以提升，我已经几个月没更新过了，因为没什么人用，过几天有空维护一下

但前提是：
这个项目爬的都是免费代理，再怎么提升，质量也不会多高
如果拿去爬流行网站效果更差，`4000多个真正可用的不到10%`的意思是对你的目标网站可用不到10%，因为这些代理可能早就被人用过而且被你的目标网站屏蔽掉了

谢谢反馈

**Comment by Karmenzind** [comment]
@amhoho  目前我这边比较忙，如果你感兴趣的话，欢迎pull request
