### ISSUE TITLE
抓取的IP什么时候会自动更新的?

### ISSUE THREAD

**Issue by CL545740896** [Karmenzind/fp-server#2]
运行了大概1天后，IP的质量变[图片]得很差了，成功率也很低
[图片]

**Comment by CL545740896** [comment]
![image](https://user-images.githubusercontent.com/27679586/41955464-b39c1768-7a12-11e8-8c24-302e84608401.png)

**Comment by CL545740896** [comment]
![image](https://user-images.githubusercontent.com/27679586/41955484-cd8382ce-7a12-11e8-9a6c-7424d5b9775c.png)

**Comment by Karmenzind** [comment]
试试最新版的。增加了几个靠谱的网站。
把你的配置文件贴出来。
还有你的操作系统和python版本。

**Comment by Karmenzind** [comment]
试试最新版的。增加了几个靠谱的网站。
把你的配置文件贴出来。

**Comment by CL545740896** [comment]
![image](https://user-images.githubusercontent.com/27679586/41957608-16e60584-7a1a-11e8-925e-b801b76748d4.png)
![image](https://user-images.githubusercontent.com/27679586/41957633-26ac518a-7a1a-11e8-8eeb-e2b60d1248f1.png)

**Comment by CL545740896** [comment]
![image](https://user-images.githubusercontent.com/27679586/41957669-44c648ba-7a1a-11e8-9577-547c4a91124c.png)

**Comment by CL545740896** [comment]
Python 3.5.2

**Comment by Karmenzind** [comment]
现在什么情况？启动不起来还是？
你把CONSOLE_OUTPUT关掉，然后把日志文件发上来。
我用来测试的最低环境是3.5.3

**Comment by Karmenzind** [comment]
tuple + float这个报错找到原因了，待会儿更新
拜托大哥以后说话多打几个字:joy:

**Comment by Karmenzind** [comment]
好，有问题再反馈哈。
