### ISSUE TITLE
本地代理存放数量设置无效

### ISSUE THREAD

**Issue by fcmxmk** [Karmenzind/fp-server#3]
PROXY_STORE_NUM: 50

**Comment by fcmxmk** [comment]
单http代理就爬取了65个了，还在爬取

**Comment by fcmxmk** [comment]
#telnet 37.1.43.25 53281       
Trying 37.1.43.25...
Connected to 37.1.43.25.
Escape character is '^]'.
Connection closed by foreign host.

##############################################
类似这种连接即断开的代理没做检测

**Comment by fcmxmk** [comment]
爬取下来的代理不怎么好用。逻辑里面应该是过滤掉了需要认证的代理，但是还有其他不能使用的代理被爬取下来了，比如上面我举例的那个，端口是有监听的，但是一连上就断开，刚测试了下，情况和还是一样，大佬你可以测试下。
上午提取了60个入库的http匿名代理用来测试，实际能使用的最多才十几个，而且还不是固定的那些，比如这次测试可用的，下次测试可能就不能用（连接超时设置20s），很不稳定。
还是谢谢大佬了。

**Comment by Karmenzind** [comment]
1. https://github.com/Karmenzind/fp-server/blob/master/src/proxy_spider/spiders/__init__.py#L57 所有的代理都会经过这几个网站检测，目前的爬取源没有需要认证的代理。这里面有个漏洞，就是经过这些网站检测之后不一定适用于你要访问的网站，但是目前的可用性还是很高的。后面我会增加定向检测功能。
2. 另外，免费代理这种东西本来就非常不稳定，而且生命力很短，所以才会需要大量爬取、滚动更新。
我这个并不是一次性的爬虫，而是一个服务，你需要一直开着它，动态地去获取可用代理。

明白我的意思吗？

**Comment by fcmxmk** [comment]
测试使用的代理就是刚爬取的免费代理，前后不到10min。
这种不稳定性，免费的实在不实用，已经自己部署了代理。
