### ISSUE TITLE
方便提供制作fp-server docker的教程吗？

### ISSUE THREAD

**Issue by wuyongdec** [Karmenzind/fp-server#7]
Your operating system and Python version?

Have you followed the manual and FAQ?

Paste your console output here. It will be great if you can provide a log file.

**Comment by Karmenzind** [comment]
请问你说的教程是指？

**Comment by wuyongdec** [comment]
@Karmenzind 就是把整个scrapy 打包成 docker镜像的过程

**Comment by Karmenzind** [comment]
https://hub.docker.com/r/karmenzind/fp-server/  两个tag，base + 项目代码 = stable
https://github.com/Karmenzind/fp-server/blob/master/Dockerfile

底层用了公共的Fedora镜像，然后直接在上面安装的Python和Redis服务，启动方式也比较简陋，还没优化过 = = 

有人反馈太耗资源，正在考虑换成更轻的底层，busybox、debian什么的

**Comment by Karmenzind** [comment]
目前服务可用性不高，有个大功能正在写
如果你不急着用，可以先关注，等待我后续更新哈

**Comment by wuyongdec** [comment]
@Karmenzind 思路不错，学习一下
