### ISSUE TITLE
感谢一波

### ISSUE THREAD

**Issue by somewheve** [Karmenzind/fp-server#9]
Your operating system and Python version?
centos7 
版本为python34-->python36 

成功用nginx + 代码 部署在服务器上面
其中遇到坑就是需要安装python36-devel  安装python-redis插件需要这个 。
感谢大佬 

还有就是能不能在返回的字段加入返回的延时啊  
还有有个代理叫31代理 网址是http://31f.cn/

**Comment by Karmenzind** [comment]
谢谢反馈，会继续改进 :handshake:

安装环境麻烦的话，可以用Docker来部署
至于时延，我还没有写出一个比较好的计算方法，后续会加上

**Comment by Karmenzind** [comment]
运行正常吗？
之前有个issue是关于阿里云+centos7的https://github.com/Karmenzind/fp-server/issues/4

**Comment by somewheve** [comment]
http://120.79.160.243/api/proxy/    很稳定的

**Comment by somewheve** [comment]
还有一个就是安装python-redis插件的时一定要装python3的依赖  python3-devel 或者什么的  每个系统名字不一样

**Comment by somewheve** [comment]
他的issue太模糊  我的centos7测试是成功的 哈哈哈哈

**Comment by Karmenzind** [comment]
哈哈那就好
